# Generated by Django 3.2.7 on 2021-10-30 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20211030_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilities',
            options={'ordering': ['title'], 'verbose_name_plural': 'Facilities'},
        ),
    ]
