# Generated by Django 3.2.7 on 2021-10-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0003_alter_idstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idstatus',
            options={'ordering': ['id_status'], 'verbose_name_plural': 'ID Statuses'},
        ),
    ]
