# Generated by Django 3.2.7 on 2021-10-30 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchasingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('po_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('vat7percent', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('amount_approved', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('wht3percent', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('pre_approved_vendor', models.BooleanField(default=False)),
                ('provide3quotes', models.BooleanField(default=True)),
                ('within_MREL', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('MREL_limit', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('exceed_MREL', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('remark', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.supplier')),
            ],
        ),
    ]
