# Generated by Django 3.2.7 on 2021-10-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20211014_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkstaffdepartment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
