# Generated by Django 3.2.7 on 2021-11-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
