# Generated by Django 3.2.7 on 2021-11-06 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0008_auto_20211028_0847'),
        ('staff', '0009_remove_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people'),
        ),
    ]
