# Generated by Django 3.2.7 on 2021-11-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20211111_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
