# Generated by Django 3.2.7 on 2021-09-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=150)),
                ('cpu', models.CharField(max_length=150)),
                ('ram', models.CharField(max_length=150)),
                ('harddisk', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=150)),
                ('tag_number', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('admin_user', models.CharField(max_length=150)),
                ('admin_pass', models.CharField(max_length=150)),
                ('computer_name', models.CharField(max_length=150)),
                ('prev_tag', models.CharField(max_length=150)),
                ('acquisition', models.CharField(max_length=150)),
                ('withdraw', models.CharField(max_length=150)),
                ('asset_number', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('note', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
