# Generated by Django 3.2.7 on 2021-09-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_auto_20210916_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='acquisition',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='withdraw',
            field=models.CharField(max_length=150),
        ),
    ]
