# Generated by Django 3.2.7 on 2021-09-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_auto_20210916_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='acquisition',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='withdraw',
        ),
    ]
