# Generated by Django 3.2.7 on 2021-09-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_auto_20210916_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='updatedAt',
        ),
    ]
