# Generated by Django 3.2.7 on 2021-09-16 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0006_auto_20210916_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='computer',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
