# Generated by Django 3.2.7 on 2021-09-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0007_auto_20210916_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='admin_pass',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='admin_user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='asset_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='prev_tag',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='tag_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
