# Generated by Django 3.2.7 on 2021-10-10 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('computer', '0009_auto_20210916_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('return_dated', models.DateField(blank=True, null=True)),
                ('accessories', models.CharField(blank=True, max_length=150, null=True)),
                ('issued_by', models.CharField(blank=True, choices=[('Diaw', 'Diaw'), ('Jonathan', 'Jonathan'), ('Jo', 'Jo')], max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computer.computer')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
        ),
    ]
