# Generated by Django 3.2.7 on 2021-10-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20211010_0925'),
        ('computer', '0012_rename_return_dated_borrow_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='computer',
        ),
        migrations.AddField(
            model_name='borrow',
            name='computer',
            field=models.ManyToManyField(to='computer.Computer'),
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='staff',
        ),
        migrations.AddField(
            model_name='borrow',
            name='staff',
            field=models.ManyToManyField(to='staff.Staff'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(blank=True, choices=[('Laptop', 'Laptop'), ('All-in-one', 'All-in-one'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Document Camera', 'Document Camera'), ('Projector', 'Projector'), ('Printer', 'Printer')], max_length=100, null=True),
        ),
    ]
