# Generated by Django 3.2.7 on 2021-10-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20211010_0925'),
        ('computer', '0013_auto_20211010_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='computer',
        ),
        migrations.AddField(
            model_name='borrow',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computer.computer'),
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='staff',
        ),
        migrations.AddField(
            model_name='borrow',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
    ]
