# Generated by Django 3.2.7 on 2021-10-10 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_auto_20211010_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Laptop', 'Laptop'), ('All-in-one', 'All-in-one'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Document Camera', 'Document Camera'), ('Projector', 'Projector'), ('Printer', 'Printer')], max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('cpu', models.CharField(blank=True, max_length=150, null=True)),
                ('ram', models.CharField(blank=True, max_length=150, null=True)),
                ('harddisk', models.CharField(blank=True, max_length=150, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True)),
                ('tag_number', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('owner', models.CharField(blank=True, max_length=150, null=True)),
                ('admin_user', models.CharField(blank=True, max_length=150, null=True)),
                ('admin_pass', models.CharField(blank=True, max_length=150, null=True)),
                ('computer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('prev_tag', models.CharField(blank=True, max_length=150, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('accessories', models.CharField(blank=True, max_length=150, null=True)),
                ('issued_by', models.CharField(blank=True, choices=[('Diaw', 'Diaw'), ('Jonathan', 'Jonathan'), ('Jo', 'Jo')], max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.computer')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
        ),
    ]
