# Generated by Django 3.2.7 on 2021-10-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='status',
        ),
    ]
