# Generated by Django 3.2.7 on 2021-10-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('inventory', '0005_location_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='location',
        ),
        migrations.AddField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
