# Generated by Django 3.2.7 on 2021-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_computer_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='room',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
