# Generated by Django 3.2.7 on 2021-11-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_computer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='issued_by',
            field=models.CharField(blank=True, choices=[('Diaw', 'Diaw'), ('Jonathan', 'Jonathan'), ('Jo', 'Jo'), ('Em', 'Em Kanapot'), ('Glen', 'Glen')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(blank=True, choices=[('Laptop', 'Laptop'), ('All-in-one', 'All-in-one'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Document Camera', 'Document Camera'), ('Projector', 'Projector'), ('Printer', 'Printer'), ('TV/SmartTV', 'TV/SmartTV')], max_length=100, null=True),
        ),
    ]
