# Generated by Django 3.2.7 on 2021-10-31 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayBF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayBF', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ECAType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eca_type', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['eca_type'],
            },
        ),
        migrations.CreateModel(
            name='ECA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eca', models.CharField(blank=True, max_length=150, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('dayBF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eca.daybf')),
                ('eca_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eca.ecatype')),
            ],
        ),
    ]
