# Generated by Django 3.2.7 on 2021-10-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True)),
                ('title', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Miss', 'Miss.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Khun.', 'Khun.'), ('Dr.', 'Dr.')], max_length=25, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
