# Generated by Django 3.2.7 on 2021-10-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20211010_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('firstname',)},
        ),
    ]
