# Generated by Django 3.2.7 on 2021-10-20 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_people_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['family'],
            },
        ),
        migrations.CreateModel(
            name='LinkFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Guardian', 'Guardian')], max_length=80, null=True)),
                ('emergency', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.family')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
            options={
                'ordering': ['family'],
            },
        ),
    ]
