# Generated by Django 3.2.7 on 2021-10-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_family_linkfamilymember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkfamilymember',
            options={},
        ),
    ]
