# Generated by Django 3.2.7 on 2021-10-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20211023_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['family'], 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('firstname',), 'verbose_name_plural': 'People'},
        ),
    ]
