# Generated by Django 3.2.7 on 2021-10-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='person',
            new_name='people',
        ),
    ]
