# Generated by Django 3.2.7 on 2021-10-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_linkstaffdepartment_active'),
        ('student', '0003_course_linkstudentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
