# Generated by Django 3.2.7 on 2021-10-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20211018_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentstatus',
            options={'verbose_name_plural': 'Student Status'},
        ),
    ]
