# Generated by Django 3.2.7 on 2021-10-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_linkfamilymember_options'),
        ('student', '0006_alter_studentstatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropoffPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtype', models.CharField(blank=True, choices=[('Dropoff', 'Dropoff'), ('Pickup', 'Pickup')], max_length=80, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
