# Generated by Django 3.2.7 on 2021-10-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20211017_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobaction',
            name='description',
        ),
    ]
