# Generated by Django 3.2.7 on 2021-10-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_jobaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
