# Generated by Django 3.2.7 on 2021-10-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobaction_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobaction',
            options={'verbose_name_plural': 'Job Actions'},
        ),
        migrations.AlterModelOptions(
            name='jobstatus',
            options={'verbose_name_plural': 'Job Statuses'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name_plural': 'Job Types'},
        ),
    ]
